# this is loaded by: config/initializers/load_app_config.rb
# usage: APP_CONFIG[:show_versions_and_limits]

development:
  host: localhost
  web_server: apache
  version: 1.0.0
  show_versions_and_limits: true
  emails_from: do.not.reply@dev.com
  per_page: 12
  max_alert_history: 5000
  solr_url: http://appsudo.com:8983/solr/collection1
  # Sharing:
  share_url: http://localhost:8888
  share_api_key: youyrztm8rn7qqs9yejqulzcsm24r5f8p27bx0bdy6a
  # Reports/PDFs config:
  max_report_history: 5000
  reports_path: /Users/cleesmith/Sites/rails4/osCollect/shared/reports
  reports_url: localhost:3000
  reports_allowed_ip: 127.0.0.1
  phantomjs: /Users/cleesmith/Sites/rails4/osCollect/lib/phantomjs/phantomjs
  rasterizejs: /Users/cleesmith/Sites/rails4/osCollect/lib/phantomjs/rasterize.js
  # note: a report may consist of html tables for search results as well
  #       as google charts which are grouped by search results ... a
  #       google chart may take many seconds to be rendered, so it may be
  #       necessary to increase the following if users see unfinished reports:
  phantomjs_rasterize_page_render_time_out: 10000 # 10,000 ms = 10 sec.s

production:
  host: localhost
  web_server: apache
  version: 1.0.0
  show_versions_and_limits: true
  emails_from: do.not.reply@prod.com
  per_page: 12
  max_alert_history: 5000
  solr_url: http://127.0.0.1:8983/solr/collection1
  # Sharing:
  share_url: http://localhost:8888
  share_api_key: tdrc-4sokfk6egxrsnolh9_s7zebpqtmit974axtg_s
  # Reports/PDFs config:
  max_report_history: 5000
  reports_path: /home/oscollect/apps/oscollect/shared/reports
  reports_url: 127.0.0.1
  reports_allowed_ip: 127.0.0.1
  phantomjs: /usr/local/bin/phantomjs
  rasterizejs: /home/oscollect/apps/oscollect/current/lib/phantomjs/rasterize.js
  # note: a report may consist of html tables for search results as well
  #       as google charts which are grouped by search results ... a
  #       google chart may take many seconds to be rendered, so it may be
  #       necessary to increase the following if users see unfinished reports:
  phantomjs_rasterize_page_render_time_out: 10000 # 10,000 ms = 10 sec.s
