# cron info:
# Input consists of six fields, separated by blanks.
# The first five give a date and time in the following form:
# 1. m - minute, expressed as a number from 0 through 59.
# 2. h - hour, expressed as a number from 0 through 23.
# 3. D - day of the month, expressed as a number from 1 through 31.
# 4. M - month of the year, expressed as a number from 1 through 12.
# 5. WD - day of the week, expressed as a number from 0 through 6 (with 0 standing for Sunday).
# Any of these fields may contain an asterisk * standing for all possible values.
# For example, if you have an * as the day of the month, the job runs every day of the month.
# A field can also contain a set of numbers separated by commas, or a range of numbers, with the
# first number followed by a minus sign - followed by the second number.
# If you give specific days for both day of the month and day of the week, the two are OR'ed together.
# examples:
# 1 2 3 4 5
# m h D M WD
# 0 0 * * * -- midnight every day
# 0 0 * * 1-5 -- midnight every weekday
# 0 0 1,15 * * -- midnight on 1st and 15th of month
# 0 0 1 * 5 -- midnight on 1st of month and every Friday
# The sixth field of a crontab entry is a string that your shell executes at the specified time.

process_alerts:
  every: 1m
  class: AlertWorker
  queue: oscollect_alerts
  args: "none"
  description: "Alerts"
  rails_envs: development, production

# 2013/01/24: no longer do hourly reports
# process_hourly_reports:
#   every: 1h
#   class: HourlyReportWorker
#   queue: oscollect_hourly_reports
#   args: "none"
#   description: "Hourly Reports"
#   rails_envs: development, production

process_daily_reports:
  # "0 1 * * *" == 1am every day, but it is really the daily report for yesterday
  cron: "0 1 * * *"
  class: DailyReportWorker
  queue: oscollect_daily_reports
  args: "none"
  description: "Daily Reports"
  rails_envs: development, production

process_daily_log_counts:
  # "5 0 * * *" == 12:05am every day
  cron: "5 0 * * *"
  class: DailyLogCountsWorker
  queue: oscollect_daily_log_counts
  args: "none"
  description: "Daily Log Counts"
  rails_envs: development, production

process_weekly_reports:
  # "0 2 * * 0" == 2am every Sunday, but it is really the weekly report for last week
  cron: "0 2 * * 0"
  class: WeeklyReportWorker
  queue: oscollect_weekly_reports
  args: "none"
  description: "Weekly Reports"
  rails_envs: development, production

process_weekly_log_counts:
  # "15 0 * * 0" == 12:15am every Sunday
  cron: "15 0 * * 0"
  class: WeeklyLogCountsWorker
  queue: oscollect_weekly_log_counts
  args: "none"
  description: "Weekly Log Counts"
  rails_envs: development, production

delete_old_logs:
  # "0 3 * * *" == 3am every day, ensure this is the last job performed
  cron: "0 3 * * *"
  class: DeleteLogsWorker
  queue: oscollect_delete_logs
  args: "none"
  description: "Delete Logs"
  rails_envs: development, production
